# Generated by Django 3.2.3 on 2021-09-18 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1500)),
                ('video', models.FileField(upload_to='videos')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
            ],
        ),
    ]
