# Generated by Django 3.2.3 on 2021-09-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='view',
            new_name='views',
        ),
    ]
