# Generated by Django 3.2.3 on 2021-09-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_video_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
    ]
