# Generated by Django 3.2.3 on 2021-09-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_comment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-date']},
        ),
    ]
